configData = {
  numChatMax        : 30,
  personalColor     : false,
  badgeVisible      : true,
  badgeChannelId    : 0,
  themeURI          : "",
  theme             : "rim",
  themeName         : "RimWorld",
  msgExistDuration  : 60,
  msgAniDuration    : 5,
  debugLevel        : 1,
  useDisplayName    : true,
  loadCheerImgs     : true,
  loadTwitchCons    : true,
  consRealSubsOnly  : true,
  loadDcCons        : true,
  dcConsURI         : "https://tv.telk.kr/js/",
  subMonthsMsg      : "☆ {!0:{months} 개월 }구독{0: 시작}! ☆",
  cheersMsg         : "☆ {!0:{bits} 비트 }후원 ! ☆",
  clipReplaceMsg    : "<img src=\"https://tv.telk.kr/images/telk/텔크클립.png\" class=\"dccon\"><br />클립이 등록되었습니다!",
  linkReplaceMsg    : "[ 링크 ]",
  webSocket         : "wss://irc-ws.chat.twitch.tv:443",
  nick              : "justinfan16831",
  pass              : "foobar",
  channel           : "#telk5093",
  retryInterval     : 2,
  allMessageHandle  : true,
  muteUser          : ["Nightbot", "OpenRCT2", "Open_RCT2", "Twipkr", "TELKbot"],
  deleteBanMsg      : true,
  commands          : [
    {exe:"clear", msg:"!clear"},
    {exe:"theme", msg:"!theme"},
    {exe:"load",  msg:"!load"}
  ],
  replaceMsgs       : [
		{orig: /\*\*(.+?)\*\*/g,    to: '<b>$1</b>'},
		{orig: /\'\'(.+?)\'\'/gi,   to: '<i>$1</i>'},
		{orig: /__(.+?)__/gi,       to: '<u>$1</u>'},
		{orig: /\-\-(.+?)\-\-/gi,   to: '<s>$1</s>'},
		{orig: /~~(.+?)~~/gi,       to: '<del>$1</del>'},
		{orig: /\^\^(.+?)\^\^/gi,   to: '<sup>$1</sup>'},
		{orig: /,,(.+?),,/gi,       to: '<sub>$1</sub>'},
		{orig: /\[br\]/gi,          to: '<br />'},

		{orig: /^!(tts(f|m)|mijin|jinho|clara|matt|yuri|shinji|meimei|liangliang|carmen|jose|google|유리|신지|구글|sy|서연) (.+?)/,
                                to: '&lt;$1&gt; $3'},
//		{orig: /^!!tts/,          to: '{no_display}'},
//		{orig: /^![a-zA-Z]+/,     to: '{no_display}'},
		{orig: /^!(sr|ㄴㄱ|신청) /, to: '{no_display}'},

		// 봇 호출 영문 메세지 미표시
		{orig: /^![^!?]+/,          to: '{no_display}'},

		// 텔하,트하,텔바,트바
		{orig: /~?리텔(-|ㅡ)?(하|바)/gm, to: '~리텔크$2'},
		{orig: /~?텔(-|ㅡ)?(하|바)/gm, to: '~텔$2'},
		{orig: /~?트(-|ㅡ)?(하|바)/gm, to: '~트$2'},
		{orig: /([\w가-힣])~(텔하|트하|텔바|트바)([\w가-힣])/gm, to: '$1$2$3'},
  ]
};
